[package]
name = "parser"
version = "0.1.0"
authors = ["donfranke"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
dict = "0.1.5"
uuid = { version = "0.8", features = ["serde", "v4"]}
